### ISSUE TITLE
Does this work with ESP32 or only ESP32-S3

### ISSUE THREAD

**Issue by dabu667** [JmanNZ/YoRadio#2]
Also, what IDE version and ESP core version did you used to complie this?

**Comment by JmanNZ** [comment]
> Also, what IDE version and ESP core version did you used to complie this?
IDE Version 1.8.19
ESP core 2.0.15

This is for ESP32-S3 only as the original was for ESP32 only

**Comment by dabu667** [comment]
Thank you, I will reproduce the environment and try to compile it for ESP32.
